# See https://github.com/SeleniumHQ/docker-selenium#via-docker-compose
version: '2'
services:
  dotnet:
    build: ./Comments
    container_name: dotnet
    ports:
      - "5000:5000"
    expose: 
      - "5000"