# See https://github.com/SeleniumHQ/docker-selenium#via-docker-compose
version: '2'
services:
  firefox:
    image: selenium/node-firefox:3.11.0-antimony
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  chrome:
    image: selenium/node-chrome:3.11.0-antimony
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:3.11.0-antimony
    container_name: selenium_hub
    ports:
      - "4444:4444"
    expose:
      - "4444"

  tests:
    build: .
    links:
      - hub
    
  comments:
    build: ./../Comments/
    environment:
      - DEFAULT_CONNECTION
      - FEEDS_APIKEY
      - FEEDS_BASEPATH
      - FEEDS_CHAPTER
      - FEEDS_DETAIL
      - FEEDS_LIST
      - GILLIAM_CLIENT_CERTIFICATE_BASE64
      - GILLIAM_BASE_PATH
      - GILLIAM_GET_CLAIMS_URL
      - GILLIAM_REALM
