# See https://github.com/SeleniumHQ/docker-selenium#via-docker-compose
version: '2'
services:
  firefox:
    image: selenium/node-firefox:3.11.0-dysprosium
    # See https://github.com/SeleniumHQ/docker-selenium#running-the-images
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  chrome:
    image: selenium/node-chrome:3.11.0-dysprosium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      #NODE_MAX_INSTANCES: 2

  # Selenium Grid/Hub
  hub:
    image: selenium/hub:3.11.0-dysprosium
    container_name: selenium_hub
    environment:
      GRID_DEBUG: "true"
      #GRID_MAX_SESSION: 2
#    ports:
#      - 4444:4444

  # The tests themselves
  tests:
    build: .
    volumes:
      - ./:/tests
      - /tests/node_modules
    links:
      - hub
      - comments
    environment:
      - ACCOUNTS_EMAIL
      - ACCOUNTS_EMAIL2
      - ACCOUNTS_EMAIL3
      - ACCOUNTS_PASSWORD

  # Comment Collection dotnet core web app
  comments:
    build: ./../Comments/
    links:
      - database
    # Enable browsing from the host machine on http://localhost:8080/consultations
    ports:
        - 8080:8080
    environment:
      - DEFAULT_CONNECTION
      - LOGGING_LOG_FILE_PATH=logs/Serilog-{Date}.json
      - APPSETTINGS_ENVIRONMENT_NAME=DockerTests
      - APPSETTINGS_ENVIRONMENT_SECURESITE=false
      - APPSETTINGS_ENVIRONMENT_REALM=niceorg
      - INDEV_APIKEY
      - INDEV_BASEPATH
      - INDEV_CHAPTER
      - INDEV_DETAIL
      - INDEV_LIST
      - GILLIAM_CLIENT_CERTIFICATE_BASE64
      - GILLIAM_BASE_PATH
      - GILLIAM_GET_CLAIMS_URL
      - GILLIAM_REALM
    networks:
      default:
        aliases:
          - niceorg

  # MS SQL Server database
  database:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_SA_PASSWORD
    ports:
      - 1434:1433
