# See https://github.com/SeleniumHQ/docker-selenium#via-docker-compose
version: '2'
services:
  firefox:
    image: selenium/node-firefox:3.11.0-dysprosium
    # See https://github.com/SeleniumHQ/docker-selenium#running-the-images
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  chrome:
    image: selenium/node-chrome:3.11.0-dysprosium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  # Selenium Grid/Hub
  hub:
    image: selenium/hub:3.11.0-dysprosium
    container_name: selenium_hub
    ports: 
      - 4444:4444

  # The tests themselves
  tests:
    build: .
    links:
      - hub
      - comments
    
  # Comment Collection dotnet core web app
  comments:
    build: ./../Comments/
    links:
      - database
    # Enable browsing from the host machine on http://localhost:8080/consultations
    ports:
        - 8080:8080
    environment:
      - DEFAULT_CONNECTION
      - LOGGING_LOG_FILE_PATH=logs/Serilog-{Date}.json
      - APPSETTINGS_ENVIRONMENT_NAME=DockerTests
      - APPSETTINGS_ENVIRONMENT_SECURESITE=false
      - APPSETTINGS_ENVIRONMENT_REALM=niceorg
      - FEEDS_APIKEY
      - FEEDS_BASEPATH
      - FEEDS_CHAPTER
      - FEEDS_DETAIL
      - FEEDS_LIST
      - GILLIAM_CLIENT_CERTIFICATE_BASE64
      - GILLIAM_BASE_PATH
      - GILLIAM_GET_CLAIMS_URL
      - GILLIAM_REALM
    networks:
      default:
        aliases:
          - niceorg

  # MS SQL Server database
  database:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_SA_PASSWORD